/// <reference types="node" />

// The MIT License (MIT)
// 
// vs-script-commands (https://github.com/mkloubert/vs-script-commands)
// Copyright (c) Marcel Joachim Kloubert <marcel.kloubert@gmx.net>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.


export const HTML_FOOTER = `

    <div id="vsscriptcommands-footer">
        <p class="vsscriptcommands-generated-by">Generated by <a href="https://github.com/mkloubert/vs-script-commands" target="_blank">vs-script-commands</a></p>

        <p class="vsscriptcommands-donate-btns">
            <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=UHVN4LRJTEXQS" title="Donate via PayPal" target="_blank">
                <img src="https://img.shields.io/badge/Donate-PayPal-green.svg">
            </a>

            <a href="https://flattr.com/submit/auto?fid=o62pkd&url=https%3A%2F%2Fgithub.com%2Fmkloubert%2Fvs-script-commands" title="Donate via Flattr" target="_blank">
                <img src="https://api.flattr.com/button/flattr-badge-large.png">
            </a>
        </p>
    </div>
  </body>
</html>`;

export const HTML_HEADER = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>[vs-script-commands] Quick execution help</title>

    <style type="text/css">

body {
    width: 100%;
}

a {
    color: inherit;
    font-weight: bold;
    text-decoration: none;
}

a:hover {
    color: white;
    text-decoration: underline;
}

h1, h2 {
    padding-bottom: 0.3em;
    border-bottom: 1px solid #333;
}

h1, h2, h3, h4, h5, h6 {
    margin-top: 24px;
    margin-bottom: 16px;
}

table {
    border-spacing: 0;
    border-collapse: collapse;
    margin-top: 0;
    margin-bottom: 16px;
    margin-right: 8px;
}

table td, table th {
    padding: 6px 13px;
    border: 1px solid #666;
}

table th {
    background-color: white;
    color: black;
    font-weight: bold;
}

table tr:nth-child(2n) {
    background-color: #333;
}

pre, p {
    margin: 8px 8px 8px 0px;
}

ul {
    display: block;
    list-style-type: disc;
    -webkit-margin-before: 1em;
    -webkit-margin-after: 1em;
    -webkit-margin-start: 0px;
    -webkit-margin-end: 0px;
    -webkit-padding-start: 40px;
}

li {
    display: list-item;
    text-align: -webkit-match-parent;
}

#vsscriptcommands-footer {
    margin-top: 32px;
}

#vsscriptcommands-footer p {
    clear: both !important;
    display: block !important;
    float: right;
    margin-bottom: 8px;
}

#vsscriptcommands-footer .vsscriptcommands-donate-btns img {
    border: 0px none transparent;
    height: 20px;
    margin-left: 8px;
    text-decoration: none;
}

#vsscriptcommands-footer .vsscriptcommands-donate-btns a {
    text-decoration: none;
}

    </style>
  </head>

  <body>

`;
